### ISSUE TITLE
What is fork repositories?

### ISSUE THREAD

**Issue by vrouco** [aaronpeikert/workshop-reproducible-research#3]

**Comment by aaronpeikert** [comment]
A fork is a copy of a repo, usally from someone who is not the author, but wan't to change the repo. He copies it to his own account and can then work on it. If he made something that he thinks is worthwhile for the original repo he can submit a [pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/). See [here for an example](https://help.github.com/articles/fork-a-repo/) and [here for generall infos](https://guides.github.com/activities/forking/)
