### ISSUE TITLE
GIT & OSF

### ISSUE THREAD

**Issue by vrouco** [aaronpeikert/workshop-reproducible-research#5]
What are the differences between them? Is it a good practice to use both? How can be complementary?

**Comment by aaronpeikert** [comment]
Since I haven't worked extensively with OSF, I just insert this comment on this question I found on the internet, which reflect relativly good what I think:

> Github is excellent.  We use it extensively at COS (https://github.com/CenterForOpenScience).  
> 
> Considering the relevant overlapping features between Github and OSF, Github does them far better and with more user control.  OSF is deliberately simplified on those aspects of the interface.  Also, the purpose of pursuing the Github add-on is to expose its great features to OSF users.  [As you point out, there is more that can be done to enrich this in the future.]
>
> The OSF model is to connect services so that the user has maximum flexibility to organize their workflow with the tools and services best suited to their needs.  For example, some of the next add-on releases will be data repositories like Amazon S3 and Dataverse (we've been talking to Databrary about this too).  So, in your OSF project, you could add a component of whichever repository fits best for your data needs, and then link that data to other services that get incorporated (e.g., analytic and visualization tools).
> 
> Finally, OSF will be an open infrastructure so that add-ons and services can be linked together by the community as there is interest and expertise available to get it done.  
> 
> In short, I don't see OSF as a replacement for other tools, but a means of helping users put those tools together to advance their research progress.

[stolen from Brian Nosek](https://groups.google.com/forum/#!topic/openscienceframework/uabhtYgtMgU)
