### ISSUE TITLE
How to merge pieces of a branch into master?

### ISSUE THREAD

**Issue by vrouco** [aaronpeikert/workshop-reproducible-research#8]
Today I found an issue which may happen to some of you someday.

Suppose you get to the office and you find that you forgot to commit and push the changes you made last night on a project. Now you're working on a different computer.

You come to this idea of creating a new branch so not stepping on the work you did yesterday. 

On the new branch you modify some parts of a .Rmd that was already in master (you're so careful not to modify parts where you worked on last night), and also create a new script with a fancy function.

Now here's the question. How can I merge (only) the new script into the master? And how can I add to the previous .Rmd the new part that I modified in the new branch, WITHOUT removing the non-commited changes I made in master before the branch was created.

**Comment by vrouco** [comment]
for the first question:
go to your desired branch, and write on terminal
git checkout <name_branch_where_file_is> "name_of_the_file"

**Comment by aaronpeikert** [comment]
In this case there is a git command that is named exactly as you're question and does exactly what you want (hint `merge`). Just do:
    git checkout master
    git merge somebranch
You can do a lot with that command, like cherry pick only some changes etc. or how to handle conflict between the two branches (modification in the same place) but we'll come to that in the 2. part
